apiVersion: v2
name: hapihub-migrator
description: HapiHub MongoDB to PostgreSQL migration tool
type: application
version: 3.0.0
appVersion: "3.2.1"
keywords:
  - migration
  - mongodb
  - postgresql
  - hapihub
  - healthcare
home: https://github.com/mycurelabs/monobase
maintainers:
  - name: MyCure
    email: devops@mycure.md
